#!/usr/bin/env bash

set -eu

repo_root="$(dirname "${BASH_SOURCE[0]}")/.."

if uv run pytest "${repo_root}" ${@+"$@"}; then
  echo 'Unittest executions succeeded'
  exit 0
else
  echo 'Errors were found whilst executing unittests (see above)'
  exit 1
fi
