global:
  # image property will be set during release
  image:
    ref: null
    repository: null
    tag: null

access-manager:
  cronjob:
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 500Mi
  enabled: false
artefact-enumerator:
  cronjob:
    resources:
      requests:
        memory: 200Mi
        cpu: 250m
      limits:
        memory: 1Gi
  enabled: false
backlog-controller:
  deployment:
    resources:
      requests:
        memory: 100Mi
        cpu: 250m
      limits:
        memory: 250Mi
  enabled: false
bdba:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 1Gi
  enabled: false
cache-manager:
  cronjob:
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1Gi
  enabled: false
clamav:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 8Gi
  enabled: false
  freshclam:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 1Gi
codeql:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 500Mi
  enabled: false
crypto:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
  enabled: false
delivery-db-backup:
  cronjob:
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 1Gi
  enabled: false
ghas:
  cronjob:
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 500Mi
  enabled: false
issue-replicator:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 1Gi
        cpu: 1000m
      limits:
        memory: 2Gi
  enabled: false
odg-operator:
  deployment:
    resources:
      requests:
        memory: 150Mi
        cpu: 50m
      limits:
        memory: 1Gi
  enabled: false
  extensionDefinitions: null
  namespaceOverride: null
osid:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 500Mi
  enabled: false
responsibles:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 512Mi
  enabled: false
sast:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 500Mi
  enabled: false
sbom-generator:
  deployment:
    annotations: []
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
  enabled: false
sla-violation-profiler:
  cronjob:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
  enabled: false
  schedule: null
  target_namespace: null
  ttl_seconds_after_finished: null
  successful_jobs_history_limit: null
  failed_jobs_history_limit: null
  backoff_limit: null
trivy:
  deployment:
    annotations: []
    nodeSelector: {} # to pin trivy pods to selected node(s)
    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 1Gi
  enabled: false
  cache:
    enabled: false
    storageClass: "" # if empty default SC is used
    size: 10Gi
    accessMode: ReadWriteMany # use RWO when pinned to a single node
