apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
      default:
        {{- toYaml .Values.limitRange.default | nindent 8 }}
